# Write a code to generate the output below, use "`linspace()`" and "`print()`"
## array([[ 0,  1,  2,  3,  4],
##       [ 5,  6,  7,  8,  9],
##       [10, 11, 12, 13, 14],
##       [15, 16, 17, 18, 19],
##       [20, 21, 22, 23, 24]])

In [1]:
import numpy as np

In [2]:
linSpaceArray = np.linspace(start = 0, stop = 24, num = 25, dtype = int)
linSpaceArray.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
linSpaceArray.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])